services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file:
      - .env

  # wordpress:
  #   build: ./requirements/wordpress

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password


networks: 
    inception:
      driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ayse/data/mariadb

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
