services:
  # nginx:
  #   image: nginx
  #   build: ./requirements/nginx

  # wordpress:
  #   build: ./requirements/wordpress

  mariadb:
    image : mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    ports:
      - 3306:3306


networks: 
    inception:

volumes:
  mariadb_data:

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
